# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nvwCxKNfFyCFhaibZuTQ4S7D0RIzEVz8
"""

# Deixei prints para ilustrar o passo a passo do método xD
# Código por: João Guilherme Sales de Oliveira (20190034570)
# Disciplina: Cálculo Numérico

def interpolarPolinomioLagrange(m,x,y,z): #número de pontos, abcissas, ordenadas e valor a interpolar
        r = 0
        i = 1
        j = 1
        
        for i in range(1,m+2):
            c=1
            d=1
        
            print(str(i) + "ªinteração")
            for j in range(1,m+2):
                if(i!=j):
                    c = c*(z-x[j-1]) # numerador do produtório
                    d = d*(x[i-1]-x[j-1]) #denominador do produtório
                    print("j = "+str(j))
                    print("c = "+str(c))
                    print("d = "+str(d))
                    
                    print("-------")
            
            r = r + y[i-1] * (c/d)
            print(r)
            print("----------------------")
            
            
        return r

x = [-1,0,2]
y = [4,1,-1]

m = 2
xp = 1
resul = interpolarPolinomioLagrange(m,x,y,xp)
print("O resultado final foi = " + str(resul))

