# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nvwCxKNfFyCFhaibZuTQ4S7D0RIzEVz8
"""

# Deixei prints para ilustrar o passo a passo do método xD
# Código por: João Guilherme Sales de Oliveira (20190034570)
# Disciplina: Cálculo Numérico

def interpolarPolinomioNewton(m,x,y,z): #número de pontos, abcissas, ordenadas, valor a inteprolar
    # r é o valor interpolado (parâmetro de saída)
    Dely = []
    i = 1
    k = 1
    
    #o dely precisa ser de tamanho m
    for i in range(0,m): Dely.append(0)
    ###
    
    
    for i in range(0,m):
        Dely[i] = y[i]

        
    ####################construção das diferenças divididas
    k = 1  #nesse caso precisa começar com 1 mesmo
    
    for k in range(k,m):
        for i in reversed( range(k,m) ):  ## o código sugere k+1 mas deu erro
            print('\n')
            print("i = " + str(i))
            print("Dely[i] - Dely[i-1] = " + str( Dely[i] - Dely[i-1] ) )
            
            print("Dely[i] = " + str( Dely[i] ) )
            print("Dely[i-1] = " + str( Dely[i-1] ) )
            
            print("x[i] - x[i-k] = " + str( x[i] - x[i-k] ) )
            print("x[i]= " + str( x[i] ) )
            print("x[i-k]= " + str( x[i-k] ) )
            
        
            #--i #passo-1########################
            Dely[i] = (Dely[i] - Dely[i-1])/(x[i] - x[i-k])
            print("Resul = " + str(Dely[i])) 
            print('----------------------')
    ########################
     
                
    #avaliação do polínômio pelo processo Horner
    r = Dely[m-1]
    
    for i in reversed(range(0,m-1)):
        print("---------PROCESSO HORNER-----------")
        print("\n")
        print("r = " + str(r))
        r = r*(z-x[i]) + Dely[i]
    
    return r

m = 5
x = [0.1000,0.3000,0.4000,0.6000,0.7000]
y = [0.3162,0.5477,0.6325,0.7746,0.8367]
xp = 0.200

resul = interpolarPolinomioNewton(m,x,y,xp)

print("O resultado final foi = " + str(resul))

